variable "H-publicsubnet" {}
variable "H-privatesubnet" {}
variable "H-datasubnet" {}
variable "region" {}
variable "cidr" {}
variable "ami" {}
variable "type" {}
variable "az" {}
variable "type_biger" {}
variable "ami_ubuntu" {}
variable "type_small" {}